name: monitoring

services:
  monitoring-grafana:
    container_name: monitoring-grafana
    restart: always
    image: grafana/grafana:12.3
    network_mode: host
    # Configure: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    volumes:
      - "grafana-data:/var/lib/grafana"

  # S3 compatible object storage
  monitoring-rustfs:
    container_name: monitoring-rustfs
    restart: always
    image: rustfs/rustfs:latest
    network_mode: host
    environment:
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_ACCESS_KEY=admin
      - RUSTFS_SECRET_KEY=admin
      - RUSTFS_CONSOLE_ENABLE=true
    volumes:
      - rustfs-data:/data

  # ----------------------------------------------------------------------------------------------------
  # Metrics and alerting components
  # ----------------------------------------------------------------------------------------------------
  monitoring-prometheus-alertmanager:
    container_name: monitoring-prometheus-alertmanager
    restart: always
    image: prom/alertmanager:v0.31.1
    network_mode: host
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml

  monitoring-victoriametrics:
    container_name: monitoring-victoriametrics
    restart: always
    image: victoriametrics/victoria-metrics:v1.135.0
    network_mode: host
    volumes:
      - "victoriametrics-data:/storage"
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
    depends_on:
      - "monitoring-prometheus-alertmanager"

  monitoring-victoriametrics-vmagent:
    container_name: monitoring-victoriametrics-vmagent
    restart: always
    image: victoriametrics/vmagent:v1.135.0
    network_mode: host
    volumes:
      - "victoriametrics-vmagent-data:/vmagentdata"
      - "./victoriametrics-vmagent/promscrape.yml:/etc/vmagent/promscrape.yml"
    command:
      - "--promscrape.config=/etc/vmagent/promscrape.yml"
      - "--remoteWrite.url=http://127.0.0.1:8428/api/v1/write"
    depends_on:
      - "monitoring-victoriametrics"

  monitoring-victoriametrics-vmalert:
    container_name: monitoring-victoriametrics-vmalert
    restart: always
    image: victoriametrics/vmalert:v1.135.0
    network_mode: host
    volumes:
      - "./victoriametrics-vmalert/alerts.yml:/etc/vmalert/alerts.yml"
    command:
      - --rule=/etc/vmalert/alerts.yml
      - --datasource.url=http://127.0.0.1:8428 # monitoring-victoriametrics
      - --remoteWrite.url=http://127.0.0.1:8428 # monitoring-victoriametrics
      - --remoteRead.url=http://127.0.0.1:8428 # monitoring-victoriametrics
      - --notifier.url=http://127.0.0.1:9093 # monitoring-prometheus-alertmanager
    depends_on:
      - "monitoring-victoriametrics"

  # ----------------------------------------------------------------------------------------------------
  # Log components
  # ----------------------------------------------------------------------------------------------------
  # Reference: https://hub.docker.com/r/apache/kafka
  # Ports Info:
  # - 9092: for external communication
  # - 29092: for internal communication
  # - 29093: for internal controller communication
  monitoring-kafka:
    container_name: monitoring-kafka
    restart: always
    image: apache/kafka:4.1.1
    network_mode: host
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://127.0.0.1:29092,CONTROLLER://127.0.0.1:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092,PLAINTEXT_INTERNAL://127.0.0.1:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  # Reference: https://github.com/kafbat/kafka-ui/blob/main/.dev/dev.yaml
  monitoring-kafka-ui:
    container_name: monitoring-kafka-ui
    restart: always
    image: ghcr.io/kafbat/kafka-ui:v1.2.0
    network_mode: host
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: monitoring-kafka:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
    depends_on:
      - monitoring-kafka

  monitoring-kafka-init-topics:
    container_name: monitoring-kafka-init-topics
    restart: "no"
    image: apache/kafka:4.1.1
    depends_on:
      - monitoring-kafka
    command:
      - bash
      - -c
      - >
        echo Initializing Kafka topics... &&
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server monitoring-kafka:29092 --create --topic mylabo-logs || echo "Already created" &&
        echo Kafka topics created successfully.

  monitoring-grafana-loki:
    container_name: monitoring-grafana-loki
    image: grafana/loki:3.5.10
    network_mode: host
    command: -config.file=/opt/grafana-loki/config.yaml
    volumes:
      - "grafana-loki-data:/loki"
      - "./grafana-loki/config.yaml:/opt/grafana-loki/config.yaml"

  monitoring-vector-aggregator:
    container_name: monitoring-vector-aggregator
    restart: always
    image: timberio/vector:0.53.0-debian
    network_mode: host
    volumes:
      - ./vector/aggregator_vector.yml:/etc/vector/vector.yml
    command: ["--config", "/etc/vector/vector.yml"]
    depends_on:
      - monitoring-kafka
      - monitoring-grafana-loki

  # ----------------------------------------------------------------------------------------------------
  # Node components
  # ----------------------------------------------------------------------------------------------------
  monitoring-vector-agent:
    container_name: monitoring-vector-agent
    restart: always
    image: timberio/vector:0.53.0-debian
    depends_on:
      - monitoring-kafka
    network_mode: host
    volumes:
      - ./vector/agent_vector.yml:/etc/vector/vector.yml
      - /var/log/journal:/var/log/journal:ro
    command: ["--config", "/etc/vector/vector.yml"]

  monitoring-prometheus-node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: monitoring-prometheus-node-exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: always
    volumes:
      - '/:/host:ro,rslave'

volumes:
  grafana-data:
  grafana-loki-data:
  victoriametrics-data:
  victoriametrics-vmagent-data:
  rustfs-data:
