[project]
name = "mylabo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fabric > 1, < 3",
    "pydantic",
    "pydantic-settings",
    "pyyaml",
    "pymysql",
    "tabulate",
    "ansible",
    "requests",
]

[project.scripts]
mylabo = "mylabo.main.mylabo.main:main"
mylabo-vm-image = "mylabo.main.labo_vm_image.main:main"

[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)
include = ["mylabo*"]  # package names should match these glob patterns (["*"] by default)
exclude = ["mylabo.tests*"]  # exclude packages matching these glob patterns (empty by default)
namespaces = false  # to disable scanning PEP 420 namespaces (true by default)

[dependency-groups]
dev = [
    "ansible-lint>=25.4.0",
    "pytest-cov>=7.0.0",
    "pytest>=8.3.5",
    "ruff>=0.13.0",
]
