- name: Gather subset
  ansible.builtin.setup:
    gather_subset:
      - distribution

- name: Setup
  ansible.builtin.include_tasks: "setup_{{ ansible_facts['distribution'] | lower }}{{ ansible_facts['distribution_major_version'] }}.yml"
