api=yes
api-key=@PDNS_AUTH_API_KEY
webserver=yes
webserver-address=0.0.0.0
webserver-allow-from=0.0.0.0/0
webserver-port=8081

launch=gmysql
gmysql-host=dns-pdns-mysql
gmysql-port=3306
gmysql-user=system
gmysql-password=@MYSQL_SYSTEM_PASSWORD
gmysql-dbname=pdns

local-address=0.0.0.0
local-port=1053
security-poll-suffix=
setgid=pdns
setuid=pdns
log-timestamp=yes
dnsupdate=yes
allow-dnsupdate-from=0.0.0.0/0, ::/0
